version: '3.8'
services:

  postgres:
    build: ./postgreswgis
    image: postgreswgis
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    restart: unless-stopped
    volumes: 
      - ./postgreswgis/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'