version: '3.8'
services:

  tensorflowcpu:
    build: ./tensorflow-cpu
    image: tensorflow-cpu
    restart: unless-stopped
    depends_on:
      - postgres
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    volumes: 
      - ../../src:/data
    ports:
      - '8888:8888'